baseURL: "https://wrong.athrvakhrbde.com"
languageCode: "en-us"
title: "Wrong"
theme: "hugo-theme-novela"

paginate: 6

social:
  twitter: "https://twitter.com/forestryio"
  github: "https://github.com/forestryio/novela-hugo-starter"
  linkedin: "https://www.linkedin.com/company/forestry.io"
  instagram: "https://www.instagram.com/forestryio/"
  dribbble: "https://dribbble.com/forestryio"

taxonomies:
  author: authors

markup:
  goldmark:
    renderer:
      unsafe: true
