baseURL: "https://wrong.athrvakhrbde.com"
languageCode: "en-us"
title: "Wrong"

# Basic build settings
disableKinds: ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

# Enable Git info for last modified date
enableGitInfo: true

# Enable raw HTML in markdown
markup:
  goldmark:
    renderer:
      unsafe: true
