baseURL: "https://wrong.athrvakhrbde.com"
languageCode: "en-us"
title: "Wrong"
theme: "hugo-theme-novela"
pygmentsstyle: 'monokai'

pagination:
  pagerSize: 6

outputs:
  home: ["HTML", "RSS", "JSON"]

taxonomies:
  author: authors

params:
  description: "Exploring unconventional perspectives on human relationships."
  hero:
    heading: "Atharva might be wrong, but..."
    maxWidth: 652
  social:
    twitter: "https://twitter.com/athrvakhrbde"
    github: "https://github.com/athrvakhrbde"

markup:
  goldmark:
    renderer:
      unsafe: true
