baseURL: "https://wrong.athrvakhrbde.com"
languageCode: "en-us"
title: "Is Atharva Wrong?"
theme: "hugo-theme-novela"
pygmentsstyle: 'monokai'

pagination:
  pagerSize: 6

outputs:
  home: ["HTML", "RSS", "JSON"]

taxonomies:
  author: Not Atharva

permalinks:
  post: /post/:title/

params:
  description: "Atharva might be wrong, but..."
  hero:
    heading: "Atharva might be wrong, but..."
    maxWidth: 652
  social:
    twitter: "https://twitter.com/athrvakhrbde"
    github: "https://github.com/athrvakhrbde"

markup:
  goldmark:
    renderer:
      unsafe: true
