baseURL: "https://wrong.athrvakhrbde.com"
languageCode: "en-us"
title: "Wrong"
theme: "hugo-theme-novela"

module:
  imports:
    - path: github.com/forestryio/hugo-theme-novela
      mounts:
        - source: layouts
          target: layouts
        - source: assets
          target: assets
        - source: static
          target: static
        - source: exampleSite/content
          target: content

params:
  description: "Welcome to Wrong"
  hero:
    heading: "Welcome to Wrong"
    maxWidth: 652
  social:
    twitter: "https://twitter.com/forestryio"
    github: "https://github.com/forestryio/novela-hugo-starter"
    linkedin: "https://www.linkedin.com/company/forestry.io"
    instagram: "https://www.instagram.com/forestryio/"
    dribbble: "https://dribbble.com/forestryio"

taxonomies:
  author: authors

markup:
  goldmark:
    renderer:
      unsafe: true
