baseURL: "https://wrong.athrvakhrbde.com/"
languageCode: "en-us"
title: "Wrong"
theme: "hugo-theme-novela"
pygmentsstyle: 'monokai'

paginate: 6

outputs:
  home: ["HTML", "RSS", "JSON"]

params:
  description: "Exploring unconventional perspectives on human relationships"
  hero:
    heading: "Atharva might be wrong, but..."
    maxWidth: 652

social:
  twitter: "https://twitter.com/athrvakhrbde"
  github: "https://github.com/athrvakhrbde"
  linkedin: "https://www.linkedin.com/company/forestry.io"
  instagram: "https://www.instagram.com/forestryio/"
  dribbble: "https://dribbble.com/forestryio"

taxonomies:
  author: authors

markup:
  goldmark:
    renderer:
      unsafe: true
