baseURL: "https://wrong.athrvakhrbde.com"
languageCode: "en-us"
title: "Wrong"
theme: "hugo-theme-novela"
pygmentsstyle: 'monokai'

paginate: 6

outputs:
  home: ["HTML", "RSS", "JSON"]

social:
  twitter: "https://twitter.com/athrvakhrbde"
  github: "https://github.com/athrvakhrbde"

taxonomies:
  author: authors

params:
  description: "Exploring unconventional perspectives on human relationships."
  hero:
    heading: "Atharva might be wrong, but..."
    maxWidth: 652

markup:
  goldmark:
    renderer:
      unsafe: true

  social:
    - name: twitter
      url: "https://twitter.com/athrvakhrbde"
    - name: github
      url: "https://github.com/athrvakhrbde"
