[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.121.0"
GO_VERSION = "1.21.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "20"
GIT_LFS_SKIP_SMUDGE = "1"  # Add this line if using Git LFS

# Add the following lines if using SSH keys for authentication
GIT_SSH_KEY = "your-ssh-key"
GIT_SSH_KEY_PATH = "/path/to/your/ssh-key"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[context.production.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[dev]
framework = "hugo"
targetPort = 1313

[context.production]
  command = "git submodule update --init --recursive && hugo"

[context.deploy-preview]
  command = "hugo --gc --minify --buildDrafts --buildFuture"
  publish = "public"

[context.branch-deploy]
  command = "hugo --gc --minify"
  publish = "public"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
