[build]
publish = "public"
command = "hugo"
branch = "main"  # Ensure this matches the default branch name of the repository

[build.environment]
HUGO_VERSION = "0.121.0"
GO_VERSION = "1.21.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[context.production.environment]
HUGO_ENV = "production"

[dev]
framework = "hugo"
targetPort = 1313
