backend:
  name: github
  repo: athrvakhrbde/wrong2
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "main"
    label: "Main Content"
    files:
      - label: "Site Content"
        name: "content"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "hero", widget: "image", required: false } 