backend:
  name: git-gateway
  branch: main
  repo: athrvakhrbde/wrong2
  site_domain: wrong.athrvakhrbde.com
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads

site_url: https://wrong.athrvakhrbde.com
display_url: https://wrong.athrvakhrbde.com
logo_url: /images/logo.png

local_backend: false

collections:
  - name: "post"
    label: "Posts"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    preview_path: "post/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Image", name: "hero", widget: "image"}
      - {label: "Authors", name: "authors", widget: "list", default: ["Wrong Team"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: []} # New field added

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Section", name: "hero", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Max Width", name: "maxWidth", widget: "number", default: 652},
              {label: "Background Image", name: "backgroundImage", widget: "image"}
            ]}
          - {label: "Body", name: "body", widget: "markdown"}